services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=models/best_model.pkl
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: credit_risk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
